# Generated by Django 2.0 on 2017-12-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
